on:
  push:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: set_web_app_install_dir
        run: echo "export WEB_APP_INSTALL_DIR=/opt" > /tmp/web_vars.sh
      - name: set_web_app_name
        run: echo "export WEB_APP_NAME=viam-web-demo" >> /tmp/web_vars.sh
      - name: get_artifacts
        if: github.event_name == 'release'
        run: wget https://github.com/shawnbmccarthy/viam-web-demo/archive/refs/tags/${{github.ref_name}}.tar.gz -O /tmp/viam-web-demo-${{github.ref_name}}.tar.gz
      - name: set_web_app_verison
        if: github.event_name == 'release'
        run: echo "export WEB_APP_VERSION=${{github.ref_name}}" >> /tmp/web_vars.sh
      - uses: actions/checkout@v3
      - name: build
        if: github.event_name == 'release'
        run: mv /tmp/web_* . && tar -czf module.tar.gz main.py requirements.txt run.sh components web_vars.sh web_app.tar.gz
      - uses: viamrobotics/upload-module@v1
        if: github.event_name == 'release'
        with:
          module-path: module.tar.gz
          platform: linux/amd64 
          version: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
      - uses: viamrobotics/upload-module@v1
        if: github.event_name == 'release'
        with:
          module-path: module.tar.gz
          platform: linux/arm64 
          version: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
      - uses: viamrobotics/upload-module@v1
        if: github.event_name == 'release'
        with:
          module-path: module.tar.gz
          platform: darwin/arm64 
          version: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
      - uses: viamrobotics/upload-module@v1
        if: github.event_name == 'release'
        with:
          module-path: module.tar.gz
          platform: darwin/amd64 
          version: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
